_target_: src.models.UNiFMIR_fluorescenceInfer.UNiFluorInferModule

# TODO: put my model here and specify the load-order or pre-training parameters as one of the settings here....

optimizer:
  _target_: torch.optim.Adam
  _partial_: true
  lr: ${model.args.lr}
  weight_decay: 0.01

scheduler:
  _target_: torch.optim.lr_scheduler.ReduceLROnPlateau
  _partial_: true
  mode: min
  factor: 0.57 ### 0.57 ** 4 roughly is 0.1...
  patience: 20



net:
  _target_: src.models.components.my_UNiFMIR_variant.My_UNiFMIR_variant # src.models.components.UniFMIR.Unimodel


    #  weights_to_load_in_order: ["/home/david/store1/david/lookingIntoPreTrainedMaterial_d6M1y2024tzET/data/modelAndExapleData_UNiFMIR/experiment/SwinIR2t3_stage2VCD/model_best17.pt"
    # , "/home/david/store1/david/lookingIntoPreTrainedMaterial_d6M1y2024tzET/data/modelAndExapleData_UNiFMIR/experiment/SwinIRproj2stg_enlcn_2npzProjection_Flywing/model_best6.pt",
  weights_to_load_in_order: [ "/home/david/store1/david/lookingIntoPreTrainedMaterial_d6M1y2024tzET/data/modelAndExapleData_UNiFMIR/experiment/Uni-SwinIR/model_best.pt"]
  unimodel:
    _target_: src.models.components.UniFMIR.Unimodel.UniModel
    img_size: 64
    depths: [6, 6, 6]
    num_heads: [6, 6, 6]
    inch: ${...args.inch}
    n_colors: ${...args.n_colors}
    n_feats: ${...args.n_feats}
    n_resblocks: ${...args.n_resblocks}
    res_scale: ${...args.res_scale}
    rgb_range: ${...args.rgb_range}
    scale: ${...args.scale}
    patch_size: ${...args.patch_size} #1
    embed_dim: 90  # 180 // 2
    window_size: 8
    mlp_ratio: 2.0
    qkv_bias: True
    qk_scale: null
    drop_rate: 0.0
    attn_drop_rate: 0.0
    drop_path_rate: 0.1
    norm_layer: "torch.nn.LayerNorm"
    patch_norm: True
    use_checkpoint: False
    num_feat: 32
    srscale: 2
    initialValForFinaleAdditionOf_x2d: -0.025 # vaguely based on some experimentation.... once it passes through the Sigmoid, it takes value 0.4938 ....
    train_finaleAdditionOf_x2d: False

  # (channels) * (x,y,z) = 1 * (322, 212, 77)

                #  , img_size=64, patch_size=1,
                #  embed_dim=180 // 2, depths=[6, 6, 6], num_heads=[6, 6, 6],
                #  window_size=8, mlp_ratio=2., qkv_bias=True, qk_scale=None,
                #  drop_rate=0., attn_drop_rate=0., drop_path_rate=0.1,
                #  norm_layer=nn.LayerNorm, patch_norm=True,
                #  use_checkpoint=False, num_feat=32, srscale=2,initialValForFinaleAdditionOf_x2d=0


# compile model for faster training with pytorch 2.0
compile: false


args:
    model : 'Uni-SwinIR'
    test_only : False
    task : 1
    resume : 0
    # pre_train : "/home/david/store1/david/lookingIntoPreTrainedMaterial_d6M1y2024tzET/data/modelAndExapleData_UNiFMIR/experiment/SwinIRIsotropic_Liver/model_best465.pt"
        # Below is for volumetric reconstruction...
    #save : 'savename'
    test_every : 1000
    print_every : 100
    data_test : 'Projection_Flywing'
    epochs : ${trainer.max_epochs}
    batch_size : 4
    patch_size : 64
    rgb_range : 1
    n_colors : 1
    datamin : 0
    datamax : 100
    loss : '1*L1'
    lr : 0.01
    decay : '100'
    cpu : False
    load : True
    n_GPUs : 1
    n_resblocks : 8
    n_feats : 32
    save_models : True
    scale : [1]
    chop : True
    self_ensemble : False
    act : 'relu'
    res_scale : 0.1
    dilation : False
    precision : 'single'
    seed : 1
    gamma : 0.5
    optimizer : 'ADAM'
    momentum : 0.9
    betas : (0.9, 0.999)
    epsilon : 1e-08
    weight_decay : 0
    gclip : 0
    inch: 50


