# @package _global_

# specify here default configuration
# order of defaults determines the order in which configs override each other
defaults:
  - _self_
  - data: mnist
  - model: mnist
  - callbacks: default
  - logger: null # set logger here or use command line (e.g. `python train.py logger=tensorboard`)
  - trainer: default
  - paths: default
  - extras: default
  - hydra: default

  # experiment configs allow for version control of specific hyperparameters
  # e.g. best hyperparameters for given model and datamodule
  - experiment: null

  # config for hyperparameter optimization
  - hparams_search: null

  # optional local config for machine/user specific settings
  # it's optional since it doesn't need to exist and is excluded from version control
  - optional local: default

  # debugging config (enable through command line, e.g. `python train.py debug=default)
  - debug: null

# task name, determines output directory path
task_name: "train"

# tags to help you identify your experiments
# you can overwrite this in experiment configs
# overwrite from command line with `python train.py tags="[first_tag, second_tag]"`
tags: ["dev"]

# set False to skip model training
train: True

# evaluate on test set, using best model weights achieved during training
# lightning chooses best weights based on the metric specified in checkpoint callback
test: True

# simply provide checkpoint path to resume training
ckpt_path: null

# seed for random number generators in pytorch, numpy and python.random
seed: 1234

args:
    model : 'Uni-SwinIR'
    test_only : False
    task : 1
    resume : 0
    pre_train : './experiment/Uni-SwinIR/model_best.pt'
    save : 'savename'
    test_every : 1000
    print_every : 100
    data_test : 'Projection_Flywing'
    epochs : 200
    batch_size : 4
    patch_size : 64
    rgb_range : 1
    n_colors : 1
    datamin : 0
    datamax : 100
    loss : '1*L1'
    lr : 0.0001
    decay : '100'
    cpu : False
    load : ''
    n_GPUs : 1
    n_resblocks : 8
    n_feats : 32
    save_models : True
    scale : [1]
    chop : True
    self_ensemble : False
    act : 'relu'
    res_scale : 0.1
    dilation : False
    precision : 'single'
    seed : 1
    gamma : 0.5
    optimizer : 'ADAM'
    momentum : 0.9
    betas : (0.9, 0.999)
    epsilon : 1e-08
    weight_decay : 0
    gclip : 0
      
